### ISSUE TITLE
'Exit Well' split doesn't always work in WitchWay

### ISSUE THREAD

**Issue by CorundumCore** [Avasam/Avasam.AutoSplitters#2]
I've needed to manually split on my last 3 runs of any%, but all the other split locations are working fine

**Comment by Avasam** [comment]
I think I've seen this one happen once to me as well. I'll try to investigate. Thanks for the report!

**Comment by Avasam** [comment]
@CorundumCore I was wrongly assuming that the elevator values get reset to 0. Which only happens *sometimes*. I simply set a timer for 168 frames (2800ms) after sending the elevator up for the final split. So it splits perfectly o the first frame of full white.

**Comment by Avasam** [comment]
For convenience, I've also made it so the timer shouldn't automatically start when the game boots up or when pressing "Continue" rather than "New Game".
